import {sum} from "../utilities/sequences";
import {fibList} from "../utilities/fibonacci";

/**
 * <p>Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with $1$ and $2$, the first $10$ terms will be:
 * $$1, 2, 3, 5, 8, 13, 21, 34, 55, 89, \dots$$</p>
 * <p>By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.</p>
 *
 * <p>Generated on 2024-08-09 from <a href='https://projecteuler.net/problem=2'>source</a></p>
 * <p><i><b>Average runtime ~0.02 ms</b></i></p>
 */
export function run(): bigint {
    return sum(fibList(4000000), (n: bigint): boolean => n % 2n == 0n);
}
