import {readdirSync} from 'fs';
import {writeFileSync} from "node:fs";

function makeRunFile(): void {
    const files: string[] = readdirSync('challenges');
    let content = "// THIS FILE IS AUTOMATICALLY GENERATED!\n\n";
    files.forEach(f => {
        const pr = f.split('.')[0];
        content += `import {run as ${pr}} from './challenges/${pr}';\n`;
    });
    content += "\n";
    const casesStrings: string[] = files.map(f => {
        const nmbr: string = f.split(".")[0].slice(1);
        return `        case ${nmbr}:\n` +
            `            console.log(p${nmbr}());\n` +
            '            break;\n';
    });
    content += 'export function runChallenge(challenge: number): void {\n' +
        '    switch (challenge) {\n' +
        casesStrings.join("") +
        '    }\n' +
        '}\n';
    writeFileSync('run.ts', content, {encoding: 'utf8'});
}

makeRunFile();