import {readdirSync} from 'fs';
import {writeFileSync} from "node:fs";

function makeRunFile(): void {
    const files: string[] = readdirSync('challenges');
    let content: string = "// THIS FILE IS AUTOMATICALLY GENERATED!\n\n";
    content += "import {solutions} from './solutions';\n";
    files.forEach((f: string): void => {
        const pr: string = f.split('.')[0];
        content += `import {run as ${pr}} from './challenges/${pr}';\n`;
    });
    content += "\n";
    const casesStrings: string[] = files.map((f: string) => {
        const nmbr: string = f.split(".")[0].slice(1);
        return `        case ${nmbr}:\n` +
            `            const s${nmbr} = p${nmbr}();\n` +
            `            if(solutions.has(${nmbr})) {\n` +
            `                s${nmbr} == solutions.get(${nmbr}) ? console.log(s${nmbr}, "Correct") : console.error(s${nmbr}, "Incorrect!");\n` +
            `            } else {\n` +
            `                console.log(s${nmbr}, "No solution to compare to");\n` +
            `            }\n` +
            '            break;\n';
    });
    content += 'export function runChallenge(challenge: number): void {\n' +
        '    switch (challenge) {\n' +
        casesStrings.join("") +
        '    }\n' +
        '}\n';
    writeFileSync('run.ts', content, {encoding: 'utf8'});
}

makeRunFile();
